/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test.tables.records;


import com.fuyo.cloud.db.biz.test.jooq.test.tables.TTest1Part;
import com.fuyo.cloud.db.biz.test.jooq.test.tables.interfaces.ITTest1Part;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTest1PartRecord extends UpdatableRecordImpl<TTest1PartRecord> implements Record5<Integer, Integer, String, LocalDateTime, Byte>, ITTest1Part {

    private static final long serialVersionUID = 563861537;

    /**
     * Setter for <code>test.t_test1_part.id</code>.
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.t_test1_part.id</code>.
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.t_test1_part.test_id</code>.
     */
    @Override
    public void setTestId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.t_test1_part.test_id</code>.
     */
    @Override
    public Integer getTestId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>test.t_test1_part.name</code>.
     */
    @Override
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.t_test1_part.name</code>.
     */
    @Override
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.t_test1_part.date_time</code>.
     */
    @Override
    public void setDateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.t_test1_part.date_time</code>.
     */
    @Override
    public LocalDateTime getDateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>test.t_test1_part.type</code>. test[start(1):开始,end(2):結束]
     */
    @Override
    public void setType(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.t_test1_part.type</code>. test[start(1):开始,end(2):結束]
     */
    @Override
    public Byte getType() {
        return (Byte) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, Byte> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, LocalDateTime, Byte> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TTest1Part.T_TEST1_PART.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TTest1Part.T_TEST1_PART.TEST_ID;
    }

    @Override
    public Field<String> field3() {
        return TTest1Part.T_TEST1_PART.NAME;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TTest1Part.T_TEST1_PART.DATE_TIME;
    }

    @Override
    public Field<Byte> field5() {
        return TTest1Part.T_TEST1_PART.TYPE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTestId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public LocalDateTime component4() {
        return getDateTime();
    }

    @Override
    public Byte component5() {
        return getType();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTestId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public LocalDateTime value4() {
        return getDateTime();
    }

    @Override
    public Byte value5() {
        return getType();
    }

    @Override
    public TTest1PartRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TTest1PartRecord value2(Integer value) {
        setTestId(value);
        return this;
    }

    @Override
    public TTest1PartRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public TTest1PartRecord value4(LocalDateTime value) {
        setDateTime(value);
        return this;
    }

    @Override
    public TTest1PartRecord value5(Byte value) {
        setType(value);
        return this;
    }

    @Override
    public TTest1PartRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, Byte value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITTest1Part from) {
        setId(from.getId());
        setTestId(from.getTestId());
        setName(from.getName());
        setDateTime(from.getDateTime());
        setType(from.getType());
    }

    @Override
    public <E extends ITTest1Part> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TTest1PartRecord
     */
    public TTest1PartRecord() {
        super(TTest1Part.T_TEST1_PART);
    }

    /**
     * Create a detached, initialised TTest1PartRecord
     */
    public TTest1PartRecord(Integer id, Integer testId, String name, LocalDateTime dateTime, Byte type) {
        super(TTest1Part.T_TEST1_PART);

        set(0, id);
        set(1, testId);
        set(2, name);
        set(3, dateTime);
        set(4, type);
    }
}
