/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITTest1 extends Serializable {

    /**
     * Setter for <code>test.t_test1.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>test.t_test1.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test.t_test1.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>test.t_test1.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>test.t_test1.date_time</code>.
     */
    public void setDateTime(LocalDateTime value);

    /**
     * Getter for <code>test.t_test1.date_time</code>.
     */
    public LocalDateTime getDateTime();

    /**
     * Setter for <code>test.t_test1.type</code>.
     */
    public void setType(Integer value);

    /**
     * Getter for <code>test.t_test1.type</code>.
     */
    public Integer getType();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITTest1
     */
    public void from(ITTest1 from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITTest1
     */
    public <E extends ITTest1> E into(E into);
}
