/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test.tables.interfaces;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITTest1Part extends Serializable {

    /**
     * Setter for <code>test.t_test1_part.id</code>.
     */
    public void setId(Integer value);

    /**
     * Getter for <code>test.t_test1_part.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>test.t_test1_part.test_id</code>.
     */
    public void setTestId(Integer value);

    /**
     * Getter for <code>test.t_test1_part.test_id</code>.
     */
    public Integer getTestId();

    /**
     * Setter for <code>test.t_test1_part.name</code>.
     */
    public void setName(String value);

    /**
     * Getter for <code>test.t_test1_part.name</code>.
     */
    public String getName();

    /**
     * Setter for <code>test.t_test1_part.date_time</code>.
     */
    public void setDateTime(LocalDateTime value);

    /**
     * Getter for <code>test.t_test1_part.date_time</code>.
     */
    public LocalDateTime getDateTime();

    /**
     * Setter for <code>test.t_test1_part.type</code>.
     */
    public void setType(Integer value);

    /**
     * Getter for <code>test.t_test1_part.type</code>.
     */
    public Integer getType();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITTest1Part
     */
    public void from(ITTest1Part from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITTest1Part
     */
    public <E extends ITTest1Part> E into(E into);
}
