/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test;


import com.fuyo.cloud.db.biz.test.jooq.test.tables.TTest1;
import com.fuyo.cloud.db.biz.test.jooq.test.tables.TTest1Part;


/**
 * Convenience access to all tables in test
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.t_test1</code>.
     */
    public static final TTest1 T_TEST1 = TTest1.T_TEST1;

    /**
     * The table <code>test.t_test1_part</code>.
     */
    public static final TTest1Part T_TEST1_PART = TTest1Part.T_TEST1_PART;
}
