/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test.tables;


import com.fuyo.cloud.db.biz.test.jooq.test.Keys;
import com.fuyo.cloud.db.biz.test.jooq.test.Test;
import com.fuyo.cloud.db.biz.test.jooq.test.tables.records.TTest1Record;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTest1 extends TableImpl<TTest1Record> {

    private static final long serialVersionUID = -2108728427;

    /**
     * The reference instance of <code>test.t_test1</code>
     */
    public static final TTest1 T_TEST1 = new TTest1();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TTest1Record> getRecordType() {
        return TTest1Record.class;
    }

    /**
     * The column <code>test.t_test1.id</code>.
     */
    public final TableField<TTest1Record, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test.t_test1.name</code>.
     */
    public final TableField<TTest1Record, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>test.t_test1.date_time</code>.
     */
    public final TableField<TTest1Record, LocalDateTime> DATE_TIME = createField(DSL.name("date_time"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>test.t_test1.type</code>.
     */
    public final TableField<TTest1Record, Integer> TYPE = createField(DSL.name("type"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>test.t_test1</code> table reference
     */
    public TTest1() {
        this(DSL.name("t_test1"), null);
    }

    /**
     * Create an aliased <code>test.t_test1</code> table reference
     */
    public TTest1(String alias) {
        this(DSL.name(alias), T_TEST1);
    }

    /**
     * Create an aliased <code>test.t_test1</code> table reference
     */
    public TTest1(Name alias) {
        this(alias, T_TEST1);
    }

    private TTest1(Name alias, Table<TTest1Record> aliased) {
        this(alias, aliased, null);
    }

    private TTest1(Name alias, Table<TTest1Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TTest1(Table<O> child, ForeignKey<O, TTest1Record> key) {
        super(child, key, T_TEST1);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public UniqueKey<TTest1Record> getPrimaryKey() {
        return Keys.KEY_T_TEST1_PRIMARY;
    }

    @Override
    public List<UniqueKey<TTest1Record>> getKeys() {
        return Arrays.<UniqueKey<TTest1Record>>asList(Keys.KEY_T_TEST1_PRIMARY);
    }

    @Override
    public TTest1 as(String alias) {
        return new TTest1(DSL.name(alias), this);
    }

    @Override
    public TTest1 as(Name alias) {
        return new TTest1(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TTest1 rename(String name) {
        return new TTest1(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TTest1 rename(Name name) {
        return new TTest1(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDateTime, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
