/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test.tables.pojos;


import com.fuyo.cloud.db.biz.test.jooq.test.tables.interfaces.ITTest1Part;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTest1Part implements ITTest1Part {

    private static final long serialVersionUID = -1883908927;

    private Integer       id;
    private Integer       testId;
    private String        name;
    private LocalDateTime dateTime;
    private Integer       type;

    public TTest1Part() {}

    public TTest1Part(ITTest1Part value) {
        this.id = value.getId();
        this.testId = value.getTestId();
        this.name = value.getName();
        this.dateTime = value.getDateTime();
        this.type = value.getType();
    }

    public TTest1Part(
        Integer       id,
        Integer       testId,
        String        name,
        LocalDateTime dateTime,
        Integer       type
    ) {
        this.id = id;
        this.testId = testId;
        this.name = name;
        this.dateTime = dateTime;
        this.type = type;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public Integer getTestId() {
        return this.testId;
    }

    @Override
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }

    @Override
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @Override
    public Integer getType() {
        return this.type;
    }

    @Override
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TTest1Part (");

        sb.append(id);
        sb.append(", ").append(testId);
        sb.append(", ").append(name);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITTest1Part from) {
        setId(from.getId());
        setTestId(from.getTestId());
        setName(from.getName());
        setDateTime(from.getDateTime());
        setType(from.getType());
    }

    @Override
    public <E extends ITTest1Part> E into(E into) {
        into.from(this);
        return into;
    }
}
