/*
 * This file is generated by jOOQ.
 */
package com.fuyo.cloud.db.biz.test.jooq.test.tables.pojos;


import com.fuyo.cloud.db.biz.test.jooq.test.tables.interfaces.ITTest1;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TTest1 implements ITTest1 {

    private static final long serialVersionUID = -711430086;

    private Integer       id;
    private String        name;
    private LocalDateTime dateTime;
    private Integer       type;

    public TTest1() {}

    public TTest1(ITTest1 value) {
        this.id = value.getId();
        this.name = value.getName();
        this.dateTime = value.getDateTime();
        this.type = value.getType();
    }

    public TTest1(
        Integer       id,
        String        name,
        LocalDateTime dateTime,
        Integer       type
    ) {
        this.id = id;
        this.name = name;
        this.dateTime = dateTime;
        this.type = type;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public LocalDateTime getDateTime() {
        return this.dateTime;
    }

    @Override
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @Override
    public Integer getType() {
        return this.type;
    }

    @Override
    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TTest1 (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(dateTime);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(ITTest1 from) {
        setId(from.getId());
        setName(from.getName());
        setDateTime(from.getDateTime());
        setType(from.getType());
    }

    @Override
    public <E extends ITTest1> E into(E into) {
        into.from(this);
        return into;
    }
}
