package com.fuyo.cloud.db.biz.test.g.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class GTestPartDtoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected List<Object> joinCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected String joinClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected String groupByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected Integer rows;

    public int page = 1;

    public int pageSize = 10;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample andCriteria(Object criteria) {
        if(this.joinCriteria == null){
            this.joinCriteria = new java.util.ArrayList<>();
        }
        this.joinCriteria.add(criteria);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public List<Object> getJoinCriteria() {
        return this.joinCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public String getJoinClause() {
        return joinClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample innerJoin(String table, String ... on) {
        StringBuffer sb = new StringBuffer();
        sb.append("INNER JOIN ");
        sb.append(table);
        sb.append(" ON ");
        for (int i = 0; i < on.length; i++) {
            sb.append(on[i]);
            if (i < on.length - 1) {
                sb.append(" AND ");
            }
        }
        this.joinClause = sb.toString();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample leftJoin(String table, String ... on) {
        StringBuffer sb = new StringBuffer();
        sb.append("LEFT JOIN ");
        sb.append(table);
        sb.append(" ON ");
        for (int i = 0; i < on.length; i++) {
            sb.append(on[i]);
            if (i < on.length - 1) {
                sb.append(" AND ");
            }
        }
        this.joinClause = sb.toString();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample rightJoin(String table, String ... on) {
        StringBuffer sb = new StringBuffer();
        sb.append("RIGHT JOIN ");
        sb.append(table);
        sb.append(" ON ");
        for (int i = 0; i < on.length; i++) {
            sb.append(on[i]);
            if (i < on.length - 1) {
                sb.append(" AND ");
            }
        }
        this.joinClause = sb.toString();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public String getGroupByClause() {
        return groupByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample groupBy(String groupByClause) {
        this.groupByClause = groupByClause;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample groupBy(String ... groupByClause) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < groupByClause.length; i++) {
            sb.append(groupByClause[i]);
            if (i < groupByClause.length - 1) {
                sb.append(" , ");
            }
        }
        this.groupByClause = sb.toString();
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        GTestPartDtoExample example = new GTestPartDtoExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public GTestPartDtoExample page(Integer page, Integer pageSize) {
        this.offset = (page - 1) * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public static Criteria build() {
        GTestPartDtoExample example = new GTestPartDtoExample();
        return example.createCriteria();
    }

    private void buildOrderBy(java.util.Set<java.util.Map.Entry<String, Object>> entries) {
        if (entries == null || entries.isEmpty()) {
            return;
        }
        java.lang.String[] orderByCause = entries.stream()
                .filter(x -> java.util.regex.Pattern.matches("o(a|d)_[$_a-zA-Z]+", x.getKey()))
                .sorted((x, y) -> compareValue(x.getValue(), y.getValue()))
                .map(entry -> {
                    String expression = entry.getKey();
                    String orderPrefix = expression.substring(1, 2);
                    String propName = SQLFilter.escape(expression.substring(3));
                    String columnName = parse(propName);
                    if (columnName == null) {
                        throw new java.lang.IllegalArgumentException("\"" + propName + "\" not exist");
                    }
                    switch (orderPrefix) {
                        case "a":
                            return columnName + " asc";
                        case "d":
                            return columnName + " desc";
                        default:
                            throw new java.lang.AssertionError();
                    }
                })
                .filter(java.util.Objects::nonNull)
                .toArray(java.lang.String[]::new);
        this.orderBy(orderByCause);
    }

    private void buildWhere(Criteria urlCriteria, java.util.Set<java.util.Map.Entry<String, Object>> entries) {
        if (entries == null || entries.isEmpty()) {
            return;
        }
        for (java.util.Map.Entry<String, Object> entry : entries) {
            java.lang.String expression = entry.getKey();
            java.lang.String value = entry.getValue().toString();
            if (java.util.regex.Pattern.matches("w[a-z]{3}_[a-zA-Z$_]+", expression)) {
                buildWhereExpression(urlCriteria, expression, value);
            }
        }
    }

    private void buildWhereExpression(Criteria urlCriteria, String expression, Object value) {
        if (expression == null || "" == expression) {
            return;
        }

        String compPrefix = expression.substring(2, 4);
        String propName = SQLFilter.escape(expression.substring(5));
        String columnName = parse(propName);
        if(columnName == null){
            throw new java.lang.IllegalArgumentException("\"" + propName + "\" not exist");
        }
        switch (compPrefix) {
            case "eq":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " =", value, propName);
                }
                break;
            case "ne":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " <>", value, propName);
                }
                break;
            case "gt":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " >", value, propName);
                }
                break;
            case "ge":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " >=", value, propName);
                }
                break;
            case "lt":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " <", value, propName);
                }
                break;
            case "le":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " <=", value, propName);
                }
                break;
            case "lk":
                if (value != null) {
                    urlCriteria.addCriterion(columnName + " like", "%" + value + "%", propName);
                }
                break;
            case "in":
                if (value instanceof String) {
                    String v = (String) value;
                    if (v != null && !"".equals(v)) {
                        String[] split = v.split(",");
                        if (split != null && split.length > 0) {
                            ArrayList<String> strings = new ArrayList<>();
                            for (String s : split) {
                                strings.add(s);
                            }
                            urlCriteria.addCriterion(columnName + " in", strings, propName);
                        }
                    }
                }
                break;
            case "ep":
                urlCriteria.addCriterion(columnName + " =", "", propName);
                break;
            case "np":
                urlCriteria.addCriterion(columnName + " <>", "", propName);
                break;
            case "eu":
                urlCriteria.addCriterion(columnName + " is null");
                break;
            case "nu":
                urlCriteria.addCriterion(columnName + " is not null");
                break;
            default:
                break;
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public final Criteria buildByUrlParams(java.util.Map<String, Object> params) {
        Criteria urlCriteria = this.createCriteria();
        if (params == null || params.isEmpty()) {
            return urlCriteria;
        }
        //校验url参数
        java.util.Set<java.util.Map.Entry<String, Object>> entries = params.entrySet();

        for (java.util.Map.Entry<String, Object> entry : entries) {
            String expression = entry.getKey();
            String value = entry.getValue().toString();

            //防止sql注入
            // 防止SQL注入（因为sidx、order是通过拼接SQL实现排序的，会有SQL注入风险）
            SQLFilter.sqlInject(expression);
            SQLFilter.sqlInject(value);
        }

        //构建page参数
        this.page = (int) java.util.Optional.ofNullable(params.get("page")).orElse(1);
        this.pageSize = (int) java.util.Optional.ofNullable(params.get("limit")).orElse(10);

        //构建where
        buildWhere(urlCriteria, entries);
        // 构建 orderBy
        buildOrderBy(entries);

        return urlCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public static Criteria buildWithUrlParam(java.util.Map<String, Object> params) {
        GTestPartDtoExample example = new GTestPartDtoExample();
        return example.buildByUrlParams(params);
    }

    private static int compareValue(Object a, Object b) {
        if (a == null) {
            return -1;
        } else if (b == null) {
            return 1;
        } else {
            int _a;
            try {
                _a = Integer.parseInt(a.toString());
            } catch (Exception e) {
                return -1;
            }
            int _b;
            try {
                _b = Integer.parseInt(b.toString());
            } catch (Exception e) {
                return 1;
            }
            return Integer.compare(_a, _b);
        }
    }

    private static String parse(String column) {
        if (column != null) {
            for (GTestPartDto.Column value : GTestPartDto.Column.values()) {
                if (column.equals(value.getJavaProperty())){
                    return value.getValue();
                }
            }
        }
        return null;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria and(String ... sql) {
            String condition = "";
            for (String s : sql) {
                condition += s + " ";
            }
            addCriterion(condition);
            return (Criteria) this;
        }

        public Criteria andNotBetween(String exp, Object value1, Object value2) {
            addCriterion(exp + " not between" , value1, value2, exp );
            return (Criteria) this;
        }

        public Criteria andBetween(String exp, Object value1, Object value2) {
            addCriterion(exp + " between" , value1, value2, exp );
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdEqualToColumn(GTestPartDto.Column column) {
            addCriterion("id = " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualToColumn(GTestPartDto.Column column) {
            addCriterion("id <> " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanColumn(GTestPartDto.Column column) {
            addCriterion("id > " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("id >= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanColumn(GTestPartDto.Column column) {
            addCriterion("id < " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("id <= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTestIdIsNull() {
            addCriterion("test_id is null");
            return (Criteria) this;
        }

        public Criteria andTestIdIsNotNull() {
            addCriterion("test_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestIdEqualTo(Integer value) {
            addCriterion("test_id =", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdEqualToColumn(GTestPartDto.Column column) {
            addCriterion("test_id = " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTestIdNotEqualTo(Integer value) {
            addCriterion("test_id <>", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdNotEqualToColumn(GTestPartDto.Column column) {
            addCriterion("test_id <> " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTestIdGreaterThan(Integer value) {
            addCriterion("test_id >", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdGreaterThanColumn(GTestPartDto.Column column) {
            addCriterion("test_id > " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_id >=", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdGreaterThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("test_id >= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTestIdLessThan(Integer value) {
            addCriterion("test_id <", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdLessThanColumn(GTestPartDto.Column column) {
            addCriterion("test_id < " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTestIdLessThanOrEqualTo(Integer value) {
            addCriterion("test_id <=", value, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdLessThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("test_id <= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTestIdIn(List<Integer> values) {
            addCriterion("test_id in", values, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdNotIn(List<Integer> values) {
            addCriterion("test_id not in", values, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdBetween(Integer value1, Integer value2) {
            addCriterion("test_id between", value1, value2, "testId");
            return (Criteria) this;
        }

        public Criteria andTestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("test_id not between", value1, value2, "testId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`name` = " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`name` <> " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanColumn(GTestPartDto.Column column) {
            addCriterion("`name` > " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`name` >= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanColumn(GTestPartDto.Column column) {
            addCriterion("`name` < " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`name` <= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDateTimeIsNull() {
            addCriterion("date_time is null");
            return (Criteria) this;
        }

        public Criteria andDateTimeIsNotNull() {
            addCriterion("date_time is not null");
            return (Criteria) this;
        }

        public Criteria andDateTimeEqualTo(LocalDateTime value) {
            addCriterion("date_time =", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeEqualToColumn(GTestPartDto.Column column) {
            addCriterion("date_time = " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andDateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("date_time <>", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeNotEqualToColumn(GTestPartDto.Column column) {
            addCriterion("date_time <> " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andDateTimeGreaterThan(LocalDateTime value) {
            addCriterion("date_time >", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeGreaterThanColumn(GTestPartDto.Column column) {
            addCriterion("date_time > " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andDateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("date_time >=", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeGreaterThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("date_time >= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andDateTimeLessThan(LocalDateTime value) {
            addCriterion("date_time <", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeLessThanColumn(GTestPartDto.Column column) {
            addCriterion("date_time < " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andDateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("date_time <=", value, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeLessThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("date_time <= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andDateTimeIn(List<LocalDateTime> values) {
            addCriterion("date_time in", values, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("date_time not in", values, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("date_time between", value1, value2, "dateTime");
            return (Criteria) this;
        }

        public Criteria andDateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("date_time not between", value1, value2, "dateTime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Boolean value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`type` = " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Boolean value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`type` <> " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Boolean value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanColumn(GTestPartDto.Column column) {
            addCriterion("`type` > " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`type` >= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Boolean value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanColumn(GTestPartDto.Column column) {
            addCriterion("`type` < " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualToColumn(GTestPartDto.Column column) {
            addCriterion("`type` <= " + column.getEscapedColumnName());
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Boolean> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Boolean> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_test1_part
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        private GTestPartDtoExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        protected Criteria(GTestPartDtoExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        public GTestPartDtoExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_test1_part
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    static class SQLFilter {
        public static final String ESCAPE_START_STR = "$";

        public static final String ESCAPE_END_STR = "_";

        public static final java.util.Map<String, String> KEYWORDS;

        static {
            KEYWORDS = new java.util.HashMap<String, String>() {{
            put("mastor", "master");
            put("clr", "truncate");
            put("ins", "insert");
            put("sel", "select");
            put("del", "delete");
            put("upt", "update");
            put("def", "declare");
            put("alt", "alert");
            put("dpt", "drop");
        }};
        }

        protected static String sqlInject(String str) {
            if (isBlank(str)) {
            return null;
        }
        //去掉'|"|;|\字符
        str = str.replace("'", "");
        str = str.replace("\"", "");
        str = str.replace(";", "");
        str = str.replace("\\", "");
        //转换成小写
        str = str.toLowerCase();
        //判断是否包含非法字符
        java.util.Set<java.util.Map.Entry<String, String>> entries = KEYWORDS.entrySet();
        for (java.util.Map.Entry<String, String> entry : entries) {
            String keyword = entry.getValue();
            if (str.contains(keyword)) {
                throw new IllegalArgumentException("parameter \"" + str + "\"contains illegal characters:\"" + keyword + "\", please use escape characters:\"" + ESCAPE_START_STR + entry.getKey() + ESCAPE_END_STR + "\"");
            }
        }

        return str;
        }

        private static boolean isBlank(String str) {
            int strLen;
        if (str == null || (strLen = str.length()) == 0) {
            return true;
        }
        for (int i = 0; i < strLen; i++) {
            if ((!Character.isWhitespace(str.charAt(i)))) {
                return false;
            }
        }
        return true;
        }

        private static String escape(String str) {
            if (str == null || "".equals(str) || !str.contains(ESCAPE_START_STR) || !str.contains(ESCAPE_END_STR)) {
            return str;
        }
        java.util.Set<java.util.Map.Entry<String, String>> entries = KEYWORDS.entrySet();
        for (java.util.Map.Entry<String, String> entry : entries) {
            String esWord = entry.getKey();
            String realWord = entry.getValue();
            str = str.replace(ESCAPE_START_STR + esWord + ESCAPE_END_STR, realWord);
        }
        return str;
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1_part
         *
         * @mbg.generated
         */
        void example(GTestPartDtoExample example);
    }
}