package com.fuyo.cloud.db.biz.test.g.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_test1
 */
public class GTestDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test1.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test1.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test1.date_time
     *
     * @mbg.generated
     */
    private LocalDateTime dateTime;

    /**
     * Database Column Remarks:
     *   test[start(1):开始,end(2):結束]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test1.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    public static String TABLE = "t_test1";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test1.id
     *
     * @return the value of t_test1.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.id
     *
     * @param id the value for t_test1.id
     *
     * @mbg.generated
     */
    public GTestDto withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.id
     *
     * @param id the value for t_test1.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test1.name
     *
     * @return the value of t_test1.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.name
     *
     * @param name the value for t_test1.name
     *
     * @mbg.generated
     */
    public GTestDto withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.name
     *
     * @param name the value for t_test1.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test1.date_time
     *
     * @return the value of t_test1.date_time
     *
     * @mbg.generated
     */
    public LocalDateTime getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.date_time
     *
     * @param dateTime the value for t_test1.date_time
     *
     * @mbg.generated
     */
    public GTestDto withDateTime(LocalDateTime dateTime) {
        this.setDateTime(dateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.date_time
     *
     * @param dateTime the value for t_test1.date_time
     *
     * @mbg.generated
     */
    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * Database Column Remarks:
     *   test[start(1):开始,end(2):結束]
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test1.type
     *
     * @return the value of t_test1.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * Database Column Remarks:
     *   test[start(1):开始,end(2):結束]
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.type
     *
     * @param type the value for t_test1.type
     *
     * @mbg.generated
     */
    public GTestDto withType(Boolean type) {
        this.setType(type);
        return this;
    }

    /**
     * Database Column Remarks:
     *   test[start(1):开始,end(2):結束]
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test1.type
     *
     * @param type the value for t_test1.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", dateTime=").append(dateTime);
        sb.append(", type=").append(type);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GTestDto other = (GTestDto) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDateTime() == null ? other.getDateTime() == null : this.getDateTime().equals(other.getDateTime()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDateTime() == null) ? 0 : getDateTime().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    public static enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        dateTime("date_time", "dateTime", "TIMESTAMP", false),
        type("type", "type", "BIT", true);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String as() {
            return this.getEscapedColumnName() + " AS " + this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String as(String alias) {
            return this.getEscapedColumnName() + " AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String count() {
            return "COUNT(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String countAs() {
            return "COUNT(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String countAs(String alias) {
            return "COUNT(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String sum() {
            return "SUM(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String sumAs() {
            return "SUM(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String sumAs(String alias) {
            return "SUM(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String year() {
            return "YEAR(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String yearWeekMondayFirst() {
            return "YEARWEEK(date_format(" + this.getEscapedColumnName() + " , '%Y-%m-%d'),1)";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String yearWeekMondayFirstAs() {
            return "YEARWEEK(date_format(" + this.getEscapedColumnName() + " , '%Y-%m-%d'),1) AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String yearWeekMondayFirstAs(String alias) {
            return "YEARWEEK(date_format(" + this.getEscapedColumnName() + " , '%Y-%m-%d'),1) AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String yearAs() {
            return "YEAR(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String yearAs(String alias) {
            return "YEAR(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfYear() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAYOFYEAR(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d')";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfYearAs() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAYOFYEAR(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfYearAs(String alias) {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAYOFYEAR(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String quarter() {
            return "QUARTER(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String quarterAs() {
            return "QUARTER(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String quarterAs(String alias) {
            return "QUARTER(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String month() {
            return "MONTH(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String monthAs() {
            return "MONTH(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String monthAs(String alias) {
            return "MONTH(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfMonth() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAY(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d')";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfMonthAs() {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAY(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfMonthAs(String alias) {
            return "DATE_FORMAT(DATE_SUB(" + this.getEscapedColumnName() + " , INTERVAL DAY(" + this.getEscapedColumnName() + ")-1 DAY) ,'%Y-%m-%d') AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfWeek() {
            return "DATE_FORMAT(DATE_ADD(" + this.getEscapedColumnName() + " , INTERVAL -WEEKDAY(" + this.getEscapedColumnName() + ") DAY) ,'%Y-%m-%d')";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfWeekAs() {
            return "DATE_FORMAT(DATE_ADD(" + this.getEscapedColumnName() + " , INTERVAL -WEEKDAY(" + this.getEscapedColumnName() + ") DAY) ,'%Y-%m-%d') AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String firstDayOfWeekAs(String alias) {
            return "DATE_FORMAT(DATE_ADD(" + this.getEscapedColumnName() + " , INTERVAL -WEEKDAY(" + this.getEscapedColumnName() + ") DAY) ,'%Y-%m-%d') AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String day() {
            return "DAY(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dayAs() {
            return "DAY(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dayAs(String alias) {
            return "DAY(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String toDays() {
            return "TO_DAYS(" + this.getEscapedColumnName() + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String toDaysAs() {
            return "TO_DAYS(" + this.getEscapedColumnName() + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String toDaysAs(String alias) {
            return "TO_DAYS(" + this.getEscapedColumnName() + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormat(String pattern) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"" + pattern + "\")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatAs(String pattern) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"" + pattern + "\") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatAs(String pattern, String alias) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"" + pattern + "\") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMdd$() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d\")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMdd$As() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d\") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMdd$As(String alias) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d\") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMddHHmmss$() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d %T\")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMddHHmmss$As() {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d %T\") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateFormatWith$yyyyMMddHHmmss$As(String alias) {
            return "DATE_FORMAT(" + this.getEscapedColumnName() + " , \"%Y-%m-%d %T\") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateSub(String param) {
            return "DATE_SUB(" + this.getEscapedColumnName() + " , " + param + ")";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateSubAs(String param) {
            return "DATE_SUB(" + this.getEscapedColumnName() + " , " + param + ") AS " + this.getJavaProperty();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String dateSubAs(String param, String alias) {
            return "DATE_SUB(" + this.getEscapedColumnName() + " , " + param + ") AS " + alias;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String withAlias() {
            if (this.isColumnNameDelimited) {
                return "t_test1." + BEGINNING_DELIMITER + this.column + ENDING_DELIMITER;
            } else {
                return "t_test1." + this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String withAlias(String as) {
            if (this.isColumnNameDelimited) {
                return "t_test1." + BEGINNING_DELIMITER + this.column + ENDING_DELIMITER + " as " + as;
            } else {
                return "t_test1." + this.column + " as " + as;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return BEGINNING_DELIMITER + this.column + ENDING_DELIMITER;
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_test1
     *
     * @mbg.generated
     */
    public static enum Type {
        START(true, "开始"),
        END(true, "結束");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private final Boolean value;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        private final String name;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        Type(Boolean value, String name) {
            this.value = value;
            this.name = name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public Boolean getValue() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public Boolean value() {
            return this.value;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public String getName() {
            return this.name;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_test1
         *
         * @mbg.generated
         */
        public static java.util.Optional<Type> parse(Boolean value) {
            if(value==null){
                return java.util.Optional.empty();
            }
            for (Type o: values()) {
                if(o.value.equals(value)){
                    return java.util.Optional.ofNullable(o);
                }
            }
            return java.util.Optional.empty();
        }
    }
}